### ISSUE TITLE
Catalog selection field hint doesn't change

### ISSUE THREAD

**Issue by hoverkw** [yuoopwe/MovieSearchApp#22]
After decision which catalog I would like to explore hint in "Search" field doesn't change but remain the same whole time and says "Search movie" even if I want to search for game.
Beside that it has a typo.
![3](https://user-images.githubusercontent.com/62996643/151665719-296cff3e-d88b-49c0-9176-5eff95024dfe.png)

**Comment by hoverkw** [comment]
What is the state of this issue. It has been two weeks since I notified you about this problem and I do not hear anything from you. Please update me about current state.

**Comment by connorparr97** [comment]
This issue has been corrected and will be reflected in our 1.1 version update.
